// lib/services/groupService.ts
import { Group, IGroup, IGroupMember } from "@/lib/models/Group";
import { createCollection, deleteCollection } from "./rekognition";
import connectDB from "@/lib/config/database";
import mongoose from "mongoose";

export class GroupService {
  static async createGroup(
    name: string,
    creatorId: string,
    description?: string,
    autoDeleteDays?: number
  ): Promise<IGroup> {
    await connectDB();

    const inviteCode =
      Math.random().toString(36).substring(2, 15) +
      Math.random().toString(36).substring(2, 15);

    // Create AWS Rekognition collection for this group
    let rekognitionCollectionId: string | undefined;
    try {
      rekognitionCollectionId = await createCollection(
        // Group ID will be generated by MongoDB, use a temporary identifier
        inviteCode
      );
      console.log(
        `Created Rekognition collection: ${rekognitionCollectionId}`
      );
    } catch (error) {
      console.error("Failed to create Rekognition collection:", error);
      // Continue without collection - it can be created later during first upload
    }

    const group = await Group.create({
      name,
      description,
      inviteCode,
      creatorId,
      autoDeleteDays: autoDeleteDays || 30,
      rekognitionCollectionId,
      members: [
        {
          userId: new mongoose.Types.ObjectId(creatorId),
          role: "ADMIN" as const,
          permissions: {
            canUpload: true,
            canDownload: true,
            canDelete: true,
          },
          joinedAt: new Date(),
        },
      ],
    });

    // Update collection with actual group ID if collection was created
    if (rekognitionCollectionId && group._id) {
      try {
        const actualCollectionId = await createCollection(
          group._id.toString()
        );
        await Group.findByIdAndUpdate(group._id, {
          rekognitionCollectionId: actualCollectionId,
        });
        // Delete the temporary collection
        await deleteCollection(rekognitionCollectionId);
        console.log(
          `Updated to actual collection ID: ${actualCollectionId}`
        );
      } catch (error) {
        console.error("Failed to update collection ID:", error);
      }
    }

    return group;
  }

  static async getUserGroups(userId: string): Promise<IGroup[]> {
    await connectDB();

    return await Group.find({
      "members.userId": userId,
    })
      .populate("members.userId", "name email avatar")
      .sort({ createdAt: -1 });
  }

  static async getGroupById(
    groupId: string,
    userId: string
  ): Promise<IGroup | null> {
    await connectDB();

    const group = await Group.findOne({
      _id: groupId,
      "members.userId": userId,
    }).populate("members.userId", "name email avatar");

    return group;
  }

  static async joinGroup(inviteCode: string, userId: string): Promise<IGroup> {
    await connectDB();

    const group = await Group.findOne({ inviteCode });

    if (!group) {
      throw new Error("Invalid invite code");
    }

    // Check if user is already a member with proper typing
    const isAlreadyMember = group.members.some(
      (member: IGroupMember) => member.userId.toString() === userId
    );

    if (isAlreadyMember) {
      throw new Error("You are already a member of this group");
    }

    // Add user to group
    group.members.push({
      userId: new mongoose.Types.ObjectId(userId),
      role: "MEMBER" as const,
      permissions: {
        canUpload: true,
        canDownload: true,
        canDelete: false,
      },
      joinedAt: new Date(),
    });

    await group.save();
    return group;
  }

  static async deleteGroup(groupId: string, userId: string): Promise<void> {
    await connectDB();

    const group = await Group.findById(groupId);

    if (!group) {
      throw new Error("Group not found");
    }

    // Check if user is the creator
    if (group.creatorId.toString() !== userId) {
      throw new Error("Only the group creator can delete the group");
    }

    // Delete Rekognition collection if it exists
    if (group.rekognitionCollectionId) {
      try {
        await deleteCollection(
          group.rekognitionCollectionId
        );
        console.log(
          `Deleted Rekognition collection: ${group.rekognitionCollectionId}`
        );
      } catch (error) {
        console.error(
          "Failed to delete Rekognition collection:",
          error
        );
        // Continue with group deletion even if collection deletion fails
      }
    }

    // Delete the group (this will cascade delete media, faces, clusters via MongoDB)
    await Group.findByIdAndDelete(groupId);
  }
}
